image: galacticfog/docker-sbt:1.12

stages:
- test
- publish

cache:
  key: "$CI_PIPELINE_ID"
  untracked: false

test:
  stage: test
  script:
    - sbt clean update 
    - ./env-var-test.sh

docker-publish:
  stage: publish
  services:
    - docker:dind
  script: 
    - sbt docker:publish

github-publish:
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://$GITHUB_CREDENTIALS@github.com/GalacticFog/gestalt-dcos.git
    - |
      if [ -z ${CI_BUILD_TAG+x} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push -f github $CI_BUILD_TAG
      fi
  only:
    - develop
    - tags
  artifacts:

